{{- $root := . }}

{{- with .Values.geth }}
{{- if .enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $root.Release.Name }}-geth
  labels:
    {{- include "eth2-validator.labels" $root | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  serviceName: {{ $root.Release.Name }}-geth
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $root.Release.Name }}-geth
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app.kubernetes.io/component: geth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $root.Release.Name }}-geth
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        app.kubernetes.io/component: geth
    spec:
    {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "eth2-validator.geth.serviceAccountName" $root }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: geth
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          args:
            {{- $args := concat .defaultArgs .extraArgs (list (printf "--%s" .network)) }}
            {{- toYaml $args | nindent 12 }}
          ports:
            - name: jsonrpc
              containerPort: 8551
              protocol: TCP
            - name: metrics
              containerPort: 6060
              protocol: TCP
            - name: p2p-tcp
              containerPort: 30303
              protocol: TCP
              {{- if .hostPort.enabled }}
              hostPort: 30303
              {{- end }}
            - name: p2p-udp
              containerPort: 30303
              protocol: UDP
              {{- if .hostPort.enabled }}
              hostPort: 30303
              {{- end }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
          - name: data-{{ .network }}
            mountPath: /var/data
          - name: jwt-secrets
            mountPath: /var/secrets
            readOnly: true
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: jwt-secrets
        secret:
          secretName: {{ .jwtSecretName }}
  {{- if .persistent.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data-{{ .network }}
    spec:
      accessModes:
        {{- toYaml .persistent.accessModes | nindent 8 }}
      storageClassName: {{ .persistent.storageClassName }}
      resources:
        requests:
          storage: {{ .persistent.size }}
  {{- else }}
      volumes:
      - name: data
        emptyDir: {}
  {{- end }}

{{- end }}
{{- end }}
